worker_processes 1;
master_process off;
daemon off;
error_log /dev/console error;
pid /dev/null;

events {
    worker_connections 64;
    use poll;
}

http {
    default_type application/octet-stream;
    access_log off;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name localhost;

        root /mnt/fat/WWW;
        index INDEX.HTM;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
