#include "pci.h"
#include "kernel.h"
#include "paging.h"
static inline void outl(uint16_t p,uint32_t v){__asm__ volatile("outl %0,%1"::"a"(v),"Nd"(p));}
static inline uint32_t inl(uint16_t p){uint32_t v;__asm__ volatile("inl %1,%0":"=a"(v):"Nd"(p));return v;}
uint32_t pci_read_config(uint8_t b,uint8_t d,uint8_t f,uint8_t o,uint8_t s){outl(0xCF8,0x80000000u|((uint32_t)b<<16)|((uint32_t)d<<11)|((uint32_t)f<<8)|(o&0xFC));uint32_t v=inl(0xCFC)>>(8*(o&3));return s==1?v&0xFF:s==2?v&0xFFFF:v;}
void pci_write_config(uint8_t b,uint8_t d,uint8_t f,uint8_t o,uint8_t s,uint32_t v){uint32_t old=pci_read_config(b,d,f,o&0xFC,4),sh=8*(o&3),mask=s==1?0xFFu:s==2?0xFFFFu:0xFFFFFFFFu;outl(0xCF8,0x80000000u|((uint32_t)b<<16)|((uint32_t)d<<11)|((uint32_t)f<<8)|(o&0xFC));outl(0xCFC,(old&~(mask<<sh))|((v&mask)<<sh));}
static int get(uint8_t b,uint8_t d,uint8_t f,pci_device_t *p){uint32_t id=pci_read_config(b,d,f,0,4);if((id&0xFFFF)==0xFFFF)return 0;uint32_t c=pci_read_config(b,d,f,8,4);p->bus=b;p->dev=d;p->fn=f;p->vendor=id;p->device=id>>16;p->class_code=c>>24;p->subclass=c>>16;p->header_type=pci_read_config(b,d,f,0xE,1);return 1;}
static void print_bar(const pci_device_t *p,uint8_t i){uint8_t o=0x10+4*i;uint32_t v=pci_read_config(p->bus,p->dev,p->fn,o,4);if(!v)return;pci_write_config(p->bus,p->dev,p->fn,o,4,0xFFFFFFFF);uint32_t m=pci_read_config(p->bus,p->dev,p->fn,o,4);pci_write_config(p->bus,p->dev,p->fn,o,4,v);uint32_t mask=(v&1)?0xFFFFFFFCu:0xFFFFFFF0u,size=(~(m&mask))+1;kputs(" BAR");kput_dec(i);kputs((v&1)?" IO=":" MMIO=");kput_hex32(v&mask);kputs(" size=");kput_hex32(size);if(!(v&1)&&p->vendor==0x8086&&(p->device==0x100E||p->device==0x100F)){void *map=ioremap(v&mask,size,_PAGE_RW|_PAGE_PCD);kputs(" mapped=");kput_hex32((uint32_t)map);} }
void pci_find_class(uint8_t cl,uint8_t sub,pci_class_callback_t cb,void *arg){pci_device_t p;for(uint8_t b=0;b<3;b++)for(uint8_t d=0;d<32;d++){uint8_t n=1;if(get(b,d,0,&p)&&p.header_type&0x80)n=8;for(uint8_t f=0;f<n;f++)if(get(b,d,f,&p)&&p.class_code==cl&&(sub==0xFF||p.subclass==sub))cb(&p,arg);}}
void pci_init(void){pci_device_t p;kputs("[OK] PCI config mechanism #1 scan buses 0-2\n");for(uint8_t b=0;b<3;b++)for(uint8_t d=0;d<32;d++){uint8_t n=1;if(get(b,d,0,&p)&&p.header_type&0x80)n=8;for(uint8_t f=0;f<n;f++)if(get(b,d,f,&p)){kputs("[OK] PCI ");kput_dec(b);kputs(":");kput_dec(d);kputs(".");kput_dec(f);kputs(" id=");kput_hex32(((uint32_t)p.vendor<<16)|p.device);kputs(" class=");kput_hex32(((uint32_t)p.class_code<<8)|p.subclass);uint8_t bars=(p.header_type&0x7F)==0?6:2;for(uint8_t i=0;i<bars;i++)print_bar(&p,i);kputs("\n");}}}
